typography_spectrum: 0.5489669900853187
color:
  brandStrength: 0.8614139873534441
  lightness: 0.2726959178689867
  saturation: 0.834440337261185
  rhythmicContrast: 0.7916681966744363
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.05188651103526354
name: Krasse1
navigation:
  - name: Textsida 1
    id: 24458b13-80f6-472b-a623-f3042ca67b1f
    type: content
title: Test1 med TheGrid
description: 160901 /Sn
